FROM node:18-alpine

RUN apk update && apk add postgresql-client

WORKDIR /app


COPY package*.json ./

RUN npm install --legacy-peer-deps


COPY . .

# Порти для додатка та відлагодження
EXPOSE 3000
EXPOSE 9229